# Generated by Django 2.2.10 on 2020-05-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
