# Generated by Django 2.2.10 on 2020-05-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_feedback_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='marketing/images/news', verbose_name='Изображение'),
        ),
    ]
