# Generated by Django 2.2.10 on 2020-05-14 10:42

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_review_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=smartfields.fields.ImageField(upload_to='marketing/images/articles', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=smartfields.fields.ImageField(upload_to='marketing/images/news', verbose_name='Изображение'),
        ),
    ]
