# Generated by Django 2.2.10 on 2020-05-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20200511_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='doctors',
        ),
    ]
