# Generated by Django 2.2.10 on 2020-05-08 17:07

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20200508_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=smartfields.fields.ImageField(blank=True, upload_to='marketing/images/news', verbose_name='Изображение'),
        ),
    ]
