# Generated by Django 2.2.10 on 2020-05-11 09:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_remove_review_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='negatives',
            field=models.TextField(db_index=True, default='', verbose_name='Недостатки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='positives',
            field=models.TextField(db_index=True, default='', verbose_name='Достоинства'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=ckeditor.fields.RichTextField(db_index=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=ckeditor.fields.RichTextField(db_index=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='supportquestion',
            name='content',
            field=ckeditor.fields.RichTextField(db_index=True, verbose_name='Содержание'),
        ),
    ]
