# Generated by Django 2.2.10 on 2020-05-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_auto_20200511_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='negatives',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Недостатки'),
        ),
        migrations.AlterField(
            model_name='review',
            name='positives',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Достоинства'),
        ),
    ]
