# Generated by Django 2.2.10 on 2020-05-09 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0004_auto_20200508_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportquestion',
            name='patient',
        ),
        migrations.AddField(
            model_name='supportquestion',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
