# Generated by Django 2.2.10 on 2020-05-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_auto_20200509_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='content',
            field=models.TextField(db_index=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(db_index=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(db_index=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='supportquestion',
            name='content',
            field=models.TextField(db_index=True, verbose_name='Содержание'),
        ),
    ]
