# Generated by Django 2.2.10 on 2020-05-11 11:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_auto_20200511_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportquestion',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, db_index=True, null=True, verbose_name='Ответ от администрации'),
        ),
    ]
