# Generated by Django 2.2.10 on 2020-05-11 11:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_auto_20200511_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportquestion',
            name='answer',
            field=ckeditor.fields.RichTextField(blank=True, db_index=True, null=True, verbose_name='Ответ от администрации'),
        ),
        migrations.AlterField(
            model_name='supportquestion',
            name='content',
            field=ckeditor.fields.RichTextField(db_index=True, default='', verbose_name='Содержание'),
            preserve_default=False,
        ),
    ]
