# Generated by Django 2.2.2 on 2020-04-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile/images', verbose_name='Аватар'),
        ),
    ]
