# Generated by Django 2.2.10 on 2020-05-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='role',
            field=models.CharField(choices=[('Doctor', 'Доктор'), ('Patient', 'Пациент')], default='Patient', max_length=7),
        ),
    ]
