version: '3'

services:
  django:
    build: backend/.
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    expose:
      - 8000
    volumes:
      - ./:/backend
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres_bd

volumes:
  postgres_data: