version: '3'

services:
  django:
    build: ./backend
    command: gunicorn medicine_centre.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./backend/.env.dev
    volumes:
      - static_volume:/home/backend/staticfiles
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres_bd

  nginx:
    build: ./backend/nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/backend/staticfiles
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume: