version: '3'

services:
  django:
    build: ./backend
    command: gunicorn medicine_centre.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./backend/.env.dev
    volumes:
      - static:/home/backend/staticfiles
      - media:/home/backend/media
    depends_on:
      - db

  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres_bd

  react:
    build: ./frontend/react-frontend
    expose:
      - 3000
    volumes:
      - dist:/home/frontend/build

  nginx:
    build: nginx
    ports:
      - 80:80
    volumes:
      - static:/home/backend/staticfiles
      - media:/home/backend/media
      - dist:/home/frontend/build
    depends_on:
      - django
      - react

volumes:
  postgres_data:
  static:
  media:
  dist: