# Generated by Django 2.2.2 on 2020-04-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20200414_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='pub_date',
            field=models.DateTimeField(blank=True, verbose_name='Дата публикации'),
        ),
    ]
