# Generated by Django 2.2.2 on 2020-04-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='image',
        ),
    ]
