export const DOCTOR_SEARCH_URL = 'DOCTOR_SEARCH_URL';
export const NEWS_SEARCH_URL = 'NEWS_SEARCH_URL';
export const ARTICLE_SEARCH_URL = 'ARTICLE_SEARCH_URL';
export const DOCTOR_FILTER_URL = 'DOCTOR_FILTER_URL';
