# Generated by Django 2.2.2 on 2020-04-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Заголовок')),
                ('content', models.TextField(db_index=True, verbose_name='Содержание')),
                ('image', models.ImageField(upload_to='main/images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Элемент карусели',
                'verbose_name_plural': 'Элементы карусели',
                'ordering': ('title',),
            },
        ),
    ]
