# Generated by Django 2.2.2 on 2020-03-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bignews',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Большая новость', 'verbose_name_plural': 'Большие новости'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='bignews',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
