# Generated by Django 2.2.2 on 2020-03-20 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigNews',
            fields=[
                ('news_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.News')),
            ],
            options={
                'verbose_name': 'Большая новость',
                'verbose_name_plural': 'Большие новости',
                'ordering': ('pk',),
            },
            bases=('main.news',),
        ),
    ]
