# Generated by Django 2.2.2 on 2020-04-22 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=16, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Полис ОМС',
                'verbose_name_plural': 'Полисы ОМС',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(db_index=True, max_length=4, verbose_name='Серия')),
                ('number', models.CharField(db_index=True, max_length=6, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Паспорт',
                'verbose_name_plural': 'Паспорта',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.InsurancePolicy', verbose_name='Полис ОМС')),
                ('passport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.Passport', verbose_name='Паспорт')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
                'ordering': ('-user',),
            },
        ),
    ]
