# Generated by Django 2.2.2 on 2020-04-26 09:59

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='avatar',
            field=smartfields.fields.ImageField(blank=True, null=True, upload_to='lk/images', verbose_name='Аватар'),
        ),
    ]
