# Generated by Django 2.2.10 on 2020-05-11 14:42

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiplomaSpecialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Специальность по диплому',
                'verbose_name_plural': 'Специальности по диплому',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QualificationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Квалификационная категория',
                'verbose_name_plural': 'Квалификационные категории',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Высшее учебное заведение',
                'verbose_name_plural': 'Высшие учебные заведения',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('experience_from', models.CharField(max_length=4, verbose_name='Стаж работы c')),
                ('additional_education', ckeditor.fields.RichTextField(blank=True, db_index=True, null=True, verbose_name='Дополнительное образование')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Department', verbose_name='Отделение')),
                ('diploma_specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.DiplomaSpecialty', verbose_name='Специальность по диплому')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Post', verbose_name='Должность')),
                ('qualification_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.QualificationCategory', verbose_name='Квалификационная категория')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.University', verbose_name='Высшее учебное заведение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('image', smartfields.fields.ImageField(blank=True, null=True, upload_to='staff/images/certificates', verbose_name='Изображение')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('image', smartfields.fields.ImageField(blank=True, null=True, upload_to='staff/images/awards', verbose_name='Изображение')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
    ]
