# Generated by Django 2.2.10 on 2020-05-24 14:43

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiplomaSpecialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Специальность по диплому',
                'verbose_name_plural': 'Специальности по диплому',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('experience_from', models.CharField(max_length=4, verbose_name='Стаж работы c')),
                ('additional_education', ckeditor.fields.RichTextField(blank=True, db_index=True, null=True, verbose_name='Дополнительное образование')),
                ('awards', ckeditor.fields.RichTextField(blank=True, db_index=True, null=True, verbose_name='Награды')),
                ('certificates', ckeditor.fields.RichTextField(blank=True, db_index=True, null=True, verbose_name='Сертификаты')),
                ('diploma_specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.DiplomaSpecialty', verbose_name='Специальность по диплому')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3, verbose_name='Номер')),
                ('floor', models.CharField(max_length=1, verbose_name='Этаж')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
        migrations.CreateModel(
            name='QualificationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Квалификационная категория',
                'verbose_name_plural': 'Квалификационные категории',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Высшее учебное заведение',
                'verbose_name_plural': 'Высшие учебные заведения',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField(verbose_name='C')),
                ('to_time', models.TimeField(verbose_name='До')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Время приема',
                'verbose_name_plural': 'Времена приемов',
            },
        ),
        migrations.CreateModel(
            name='PrizeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', smartfields.fields.ImageField(upload_to='staff/images/prize_images', verbose_name='Изображение')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_images', to='staff.Doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Фото наград',
                'verbose_name_plural': 'Фото наград',
            },
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(blank=True, db_index=True, null=True, verbose_name='Описание')),
                ('image', smartfields.fields.ImageField(blank=True, null=True, upload_to='staff/images/posts', verbose_name='Изображение')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='staff.Department', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='doctor',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='staff.Office', verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Post', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.QualificationCategory', verbose_name='Квалификационная категория'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.University', verbose_name='Высшее учебное заведение'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
