# Generated by Django 2.2.10 on 2020-05-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='post',
        ),
        migrations.AddField(
            model_name='doctor',
            name='posts',
            field=models.ManyToManyField(related_name='doctors', to='staff.Post', verbose_name='Должности'),
        ),
    ]
