# Generated by Django 2.2.10 on 2020-05-20 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField(verbose_name='C')),
                ('to_time', models.TimeField(verbose_name='До')),
                ('date', models.DateField(verbose_name='Дата')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='Занято')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_times', to='staff.Doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Время приема',
                'verbose_name_plural': 'Времена приемов',
            },
        ),
    ]
