# Generated by Django 2.2.10 on 2020-05-11 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='staff.Doctor', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='staff.Doctor', verbose_name='Врач'),
        ),
    ]
