# Generated by Django 2.2.10 on 2020-05-12 09:18

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizeimage',
            name='image',
            field=smartfields.fields.ImageField(default='', upload_to='staff/images/prize_images', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
