# Generated by Django 2.2.10 on 2020-05-08 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ('-pk',), 'verbose_name': 'Врач', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AlterModelOptions(
            name='nurse',
            options={'ordering': ('-pk',), 'verbose_name': 'Медсестра', 'verbose_name_plural': 'Медсестры'},
        ),
    ]
