# Generated by Django 2.2.10 on 2020-05-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200511_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='qualification_Category',
            new_name='qualification_category',
        ),
    ]
