# Generated by Django 2.2.10 on 2020-06-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200527_2029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrizeImage',
        ),
    ]
