# Generated by Django 2.2.2 on 2020-03-19 10:27

import address.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
        ('user_profile', '0002_auto_20200216_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address', verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона'),
        ),
    ]
