# Generated by Django 2.2.10 on 2020-06-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reception',
            options={'ordering': ('-date', '-from_time'), 'verbose_name': 'Прием', 'verbose_name_plural': 'Приемы'},
        ),
        migrations.AddField(
            model_name='reception',
            name='confirmed_by_doctor',
            field=models.BooleanField(default=False, verbose_name='Подтвержден доктором'),
        ),
    ]
