# Generated by Django 2.2.2 on 2020-04-26 09:56

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=smartfields.fields.ImageField(upload_to='news/images/news', verbose_name='Изображение'),
        ),
    ]
